### ISSUE TITLE
Astro 5 support 

### ISSUE THREAD

**Issue by anotheri** [yeskunall/astro-umami#4]
When i install the package to astro 5 project, i get this warning:

> astro is listed by your project with version 5.0.0-beta.5 (peec57), which doesn't satisfy what @yeskunall/astro-umami and other dependencies request (^4.15.9 || ^4.15.9)

Please update `peerDependencies`

**Comment by anotheri** [comment]
@yeskunall well component worked even before the fix, so i assume it should be ok. Not sure if node 22 will affect anything but i'll be able to test it at least with SSG as soon as it's released. For some reasons have no luck to set it up with yarn via git and PR branch.

**Comment by yeskunall** [comment]
Hey, I cut a [release](https://github.com/yeskunall/astro-umami/releases/tag/v0.0.2). It’s also available on [npm](https://www.npmjs.com/package/@yeskunall/astro-umami/v/0.0.2). LMK if you run into any issues.

**PS**: I’m curious: are you using this in production? Or just testing it out? Thanks!

**Comment by anotheri** [comment]
For now just testing out, but going to use it in production soon. Is there anything i should know/worry about?

**Comment by anotheri** [comment]
@yeskunall everything looks good, thanks for quick fix 🚀

**Comment by yeskunall** [comment]
> Is there anything i should know/worry about?

Not at all. We use Astro to ship micro-sites at our agency and we use this package internally. Love seeing Astro sites in the wild—be even cooler to know if it shipped with one of our integrations. If you want, LMK once you ship to production—would love to see your site. Again, no pressure!

**Comment by artembaechka** [comment]
@yeskunall Hello! Will be package updated to astro 6? It works well with it

**Comment by yeskunall** [comment]
~@artembaechka -- damn it. [This](https://github.com/yeskunall/astro-umami/blob/main/packages/astro-umami/package.json#L46) is causing a warning to show during install, right? I’ll make a PR today. Thanks for flagging!~

Done.
